name: UNCLOUD

channels:
  - defaults
  - pytorch

dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - matplotlib
  - numpy
  - opencv
  - scikit-image
  - pillow
  - tensorboard
  - protobuf
